### ISSUE TITLE
Windows and Linux file formats

### ISSUE THREAD

**Issue by davidhanna66** [microsoft/OpenHack-FHIR#10]
If you are using Windows subsystem for Linux and bash/Ubuntu shell, and Github desktop, github desktop converts the file format to Windows/DOS.  this creates the following error:
: invalid option nameh: line 2: set: pipefail

there are 2 fixes - run git clone from subsystem for linux  - so we can supply the command
or
**run 'dos2unix ./deployhl7ingest.bash' which will convert file format.**

This is a fix for the already existing error in troubleshooting section.

**Comment by cyberuna** [comment]
Added documentation for this
