### ISSUE TITLE
Why Download Health Architectures as a Zip?

### ISSUE THREAD

**Issue by mikaelweave** [microsoft/OpenHack-FHIR#18]
I saw something curious during Challenge 2 that may be an issue. Is there a reason to have OpenHack participants download the Health Architectures repo as a zip instead of cloning/downloading it themselves directly from [that Github repo](https://github.com/microsoft/health-architectures)?

*Reasons to send the user to the repo:*
- Reduces size of OpenHack repository
- Reduces need to update the OpenHack repo when Health Architectures repo changes
- Exposes users to another repo that may help drive Health Cloud adoption

**Comment by cyberuna** [comment]
@mikaelweave This Github used to have documentation to clone Health Architectures repo but to avoid issues when new functionality is added for the sessions planned, this zip was created. Will go back to repo clone after testing code changes.

**Comment by mikaelweave** [comment]
If we are worried about new changes being introduced, we could download a version like this:
https://github.com/microsoft/health-architectures/releases/tag/v1.0

**Comment by cyberuna** [comment]
We did try v1.0, we could ask to create a new tag for the working version. Also planning to make minor changes for now and post it in that repo to get merged. This short-term approach is for the sessions planned.

**Comment by mikaelweave** [comment]
Ahhh you're already 10 steps ahead of me. 😄  Thanks for the info, really appreciate it! 

FYI I've been doing the OpenHack with the main branch of Health Architectures and filling out issues/PRs along the way. Hopefully this will help get to a stable tag we can use for the OpenHack!
