### ISSUE TITLE
Remove Credentials from health-architectures-master/ in ARM template parameters

### ISSUE THREAD

**Issue by mattpasco-microsoft** [microsoft/OpenHack-FHIR#22]
The ARM template contains client credentials and should be removed and creds should be rolled

**Comment by mattpasco-microsoft** [comment]
`OpenHack-FHIR/Scripts/health-architectures-master/Research-and-Analytics/FHIRExportwithAnonymization/Assets/arm_template.parameters.json`

**Comment by cyberuna** [comment]
Thanks, removed.
