### ISSUE TITLE
Key Vault permission issues

### ISSUE THREAD

**Issue by roshitgit** [microsoft/OpenHack-FHIR#33]
Got below warnings while completing first challenge.

WARNING: The provided information does not map to an AD object id.
WARNING: Access policy is not set. No user or application have access permission to use this vault. This can happen if the vault was
created by a service principal. Please use Set-AzKeyVaultAccessPolicy to set access policies.

**Comment by roshitgit** [comment]
i was working on first challenge using powershell scripts. all pre-requisites were completed.

**Comment by cyberuna** [comment]
Roshit, 
If it's warnings then you can ignore those.
You can also deploy using Azure CLI if you have face PS issues.
Aruna
