### ISSUE TITLE
Hack 1 documentation suggestions

### ISSUE THREAD

**Issue by davidhanna66** [microsoft/OpenHack-FHIR#4]
Postman section indicates that you should 'Import Collection' and 'Import environment'. for non-postman user this would lead me down the path of clicking import, choosing the JSON file. Postman returns not recognized format. Should specify - Click import, select Raw Text tab, and past the contents of the Collection and Enviroment files.

Also it says import collection 2x.

**Comment by cyberuna** [comment]
Updated.
