### ISSUE TITLE
Link Hygiene

### ISSUE THREAD

**Issue by Raansoon** [microsoft/OpenHack-FHIR#8]
On the prerequisite links (Challenge 00), since there are multiple links and steps, consider making the links open in a new tab or new window so the person following the instructions does not lose their instruction page when navigating to the specific pre-requisite information.

**Comment by Raansoon** [comment]
Take a look at this link format...

<a href="https://www.microsoft.com" target="_blank">Open www.microsoft.com in new tab</a>

**Comment by cyberuna** [comment]
Added note to open in new tab
